name: crm_validation
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.1
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - numexpr=2.8.4
  - bottleneck=1.3.7
  - scipy=1.10.1
  - openpyxl=3.1.2
