In [1]:
import pandas as pd

In [16]:
df1 = pd.read_csv("data/Prod/Baseline/BT_HOLD_DATA.csv", encoding='latin')
df1.head(10)

PIDM_KEY        ID HOLD_TYPE                    HOLD_DESC   
0  90048585  82307851        ZP  A&S Program Update Required  \
1  90059654  83216887        ZP  A&S Program Update Required   
2  90063838  83313379        ZP  A&S Program Update Required   
3  90068143  90110701        ZP  A&S Program Update Required   
4  90075363  97207278        ZP  A&S Program Update Required   
5  90076222  84214113        DC               CS-Dean's Hold   
6  90083908  97333520        ZP  A&S Program Update Required   
7  90084059  91107250        ZP  A&S Program Update Required   
8  90084379  97334874        ZP  A&S Program Update Required   
9  90086486  97341887        ZP  A&S Program Update Required   

        HOLD_FROM_DATE         HOLD_TO_DATE HOLD_REASON HOLD_USER  
0  2015-12-16 00:00:00  2015-12-16 14:46:48         NaN       NaN  
1  2020-11-03 00:00:00  2020-11-03 14:22:57         NaN       NaN  
2  2020-11-09 00:00:00  2020-11-09 17:20:46         NaN       NaN  
3  2018-06-02 00:00:00  2018-06-02 20:41:20         NaN       NaN  
4  2019-06-08 00:00:00  2019-07-24 10:41:48         NaN       NaN  
5  2022-11-14 00:00:00  2099-12-31 00:00:00        SCAI  JCHEDDIE  
6  2013-05-16 00:00:00  2999-12-21 00:00:00         NaN       NaN  
7  2023-02-01 00:00:00  2023-03-01 00:00:00         NaN       NaN  
8  2020-04-28 00:00:00  2022-03-03 00:00:00         NaN       NaN  
9  2013-11-18 00:00:00  2013-11-18 09:30:44         NaN       NaN

In [25]:
df1[df1.PIDM_KEY == 90206685]

PIDM_KEY         ID HOLD_TYPE                    HOLD_DESC   
13339  90206685  100078687        ZP  A&S Program Update Required  \
17754  90206685  100078687        ZP  A&S Program Update Required   
17755  90206685  100078687        ZP  A&S Program Update Required   
22034  90206685  100078687        ZP  A&S Program Update Required   

            HOLD_FROM_DATE         HOLD_TO_DATE HOLD_REASON HOLD_USER  
13339  2018-06-03 00:00:00  2018-06-11 20:02:46         NaN       NaN  
17754  2013-02-01 00:00:00  2018-06-11 20:02:46         NaN       NaN  
17755  2020-02-01 00:00:00  2999-12-21 00:00:00         NaN       NaN  
22034  2018-06-08 00:00:00  2018-06-11 20:02:46         NaN       NaN

In [27]:
df2 = pd.read_csv("data/Prod/Validate/Hold Data.csv")
df2.head()

lang_pidmkey                          lang_student    lang_id   
0      90206685  F6DD1436-3BF2-ED11-8849-000D3A84D590  100078687  \
1      90082858  2925789B-38F2-ED11-8849-002248AE080F   94322724   
2      90206685  F6DD1436-3BF2-ED11-8849-000D3A84D590  100078687   
3      90082968  C85B2413-36F2-ED11-8849-000D3AE8C6E5   91103408   
4      90206685  F6DD1436-3BF2-ED11-8849-000D3A84D590  100078687   

  lang_holdtype     lang_holddescriptionorig   
0            ZP  A&S Program Update Required  \
1            ZP  A&S Program Update Required   
2            ZP  A&S Program Update Required   
3            ZP  A&S Program Update Required   
4            ZP  A&S Program Update Required   

                   lang_holddescription            lang_holdfromdate   
0  A815C574-B4F2-ED11-8849-000D3AF3AC95  2018-06-08 00:00:00.0000000  \
1  A815C574-B4F2-ED11-8849-000D3AF3AC95  2022-06-16 00:00:00.0000000   
2  A815C574-B4F2-ED11-8849-000D3AF3AC95  2013-02-01 00:00:00.0000000   
3  A815C574-B4F2-ED11-8849-000D3AF3AC95  2019-02-01 00:00:00.0000000   
4  A815C574-B4F2-ED11-8849-000D3AF3AC95  2020-02-01 00:00:00.0000000   

               lang_holdtodate lang_holdreason lang_holduser  
0  2018-06-11 00:00:00.0000000             NaN           NaN  
1  2022-06-17 00:00:00.0000000             NaN           NaN  
2  2018-06-11 00:00:00.0000000             NaN           NaN  
3  2019-03-04 00:00:00.0000000             NaN           NaN  
4  1999-12-21 00:00:00.0000000             NaN           NaN

In [30]:
df2[df2['lang_pidmkey'] == 90206685]

lang_pidmkey                          lang_student    lang_id   
0      90206685  F6DD1436-3BF2-ED11-8849-000D3A84D590  100078687  \
2      90206685  F6DD1436-3BF2-ED11-8849-000D3A84D590  100078687   
4      90206685  F6DD1436-3BF2-ED11-8849-000D3A84D590  100078687   
6      90206685  F6DD1436-3BF2-ED11-8849-000D3A84D590  100078687   

  lang_holdtype     lang_holddescriptionorig   
0            ZP  A&S Program Update Required  \
2            ZP  A&S Program Update Required   
4            ZP  A&S Program Update Required   
6            ZP  A&S Program Update Required   

                   lang_holddescription            lang_holdfromdate   
0  A815C574-B4F2-ED11-8849-000D3AF3AC95  2018-06-08 00:00:00.0000000  \
2  A815C574-B4F2-ED11-8849-000D3AF3AC95  2013-02-01 00:00:00.0000000   
4  A815C574-B4F2-ED11-8849-000D3AF3AC95  2020-02-01 00:00:00.0000000   
6  A815C574-B4F2-ED11-8849-000D3AF3AC95  2018-06-03 00:00:00.0000000   

               lang_holdtodate lang_holdreason lang_holduser  
0  2018-06-11 00:00:00.0000000             NaN           NaN  
2  2018-06-11 00:00:00.0000000             NaN           NaN  
4  1999-12-21 00:00:00.0000000             NaN           NaN  
6  2018-06-11 00:00:00.0000000             NaN           NaN

In [10]:
df1.dtypes

PIDM_KEY           int64
ID                 int64
HOLD_TYPE         object
HOLD_DESC         object
HOLD_FROM_DATE    object
HOLD_TO_DATE      object
HOLD_REASON       object
HOLD_USER         object
dtype: object

In [36]:
pd.to_datetime(df1.HOLD_TO_DATE, format="%Y-%m-%d %H:%M:%S", errors='coerce')

0       2015-12-16 14:46:48
1       2020-11-03 14:22:57
2       2020-11-09 17:20:46
3       2018-06-02 20:41:20
4       2019-07-24 10:41:48
                ...        
34782   2099-12-31 00:00:00
34783   2099-12-31 00:00:00
34784   2099-12-31 00:00:00
34785   2023-02-17 00:00:00
34786   2023-02-17 00:00:00
Name: HOLD_TO_DATE, Length: 34787, dtype: datetime64[ns]

In [37]:
pd.to_datetime(df2.lang_holdtodate)

0       2018-06-11
1       2022-06-17
2       2018-06-11
3       2019-03-04
4       1999-12-21
           ...    
34757   2019-06-19
34758   2023-02-17
34759   2012-03-27
34760   2023-02-24
34761   2023-03-31
Name: lang_holdtodate, Length: 34762, dtype: datetime64[ns]

In [23]:
df1[df1.duplicated(subset=['PIDM_KEY', 'HOLD_TYPE', 'HOLD_FROM_DATE', 'HOLD_TO_DATE', 'HOLD_REASON', 'HOLD_USER'], keep=False)].shape

(44, 8)

In [17]:
df1.sort_values(by=['PIDM_KEY'])

PIDM_KEY         ID HOLD_TYPE                    HOLD_DESC   
28145  90001327  100001308        ZP  A&S Program Update Required  \
32398  90001327  100001308        ZP  A&S Program Update Required   
23825  90001327  100001308        ZP  A&S Program Update Required   
8869   90002371  100002349        ZP  A&S Program Update Required   
17535  90002844   84360361        ZP  A&S Program Update Required   
...         ...        ...       ...                          ...   
7662   90592643  100418532        RE            Registration Hold   
3465   90592663  100418552        RE            Registration Hold   
29061  90592729  100418618        RE            Registration Hold   
12254  90592794  100418683        IE             International Ed   
16549  90593800  100419670        RO             Registrar's Hold   

      HOLD_FROM_DATE HOLD_TO_DATE                    HOLD_REASON HOLD_USER  
28145      17-JUN-20    17-JUN-20                            NaN       NaN  
32398      08-JUN-19    17-JUN-20                            NaN       NaN  
23825      01-FEB-20    17-JUN-20                            NaN       NaN  
8869       11-FEB-20    21-DEC-99                            NaN       NaN  
17535      04-JUL-16    21-DEC-99                            NaN       NaN  
...              ...          ...                            ...       ...  
7662       31-JUL-23    31-DEC-99  Final IB Diploma + Transcript       ALY  
3465       31-JUL-23    31-DEC-99          Final SMA Certificate       ALY  
29061      31-JUL-23    31-DEC-99    Final HS Graduation Diploma       ALY  
12254      09-MAR-23    10-MAR-23       Approval Rec'd by Global    EIKARI  
16549      15-SEP-23    05-FEB-25  Concurrent Appeal 202330 ONLY  EVULCANO  

[33965 rows x 8 columns]

# Testing

- BT_HOLD_DATA -> ['PIDM_KEY', 'HOLD_TYPE', 'HOLD_FROM_DATE', 'HOLD_TO_DATE', 'HOLD_REASON', 'HOLD_USER']
- BT_TEST_SCORE -> ['PIDM_KEY', 'TEST_SCORE_CODE', 'TEST_SCORE_DATE']
- GM_ACADEMIC_HISTORY_DETAIL -> ['PIDM_KEY', 'TERM_CODE_KEY', 'CRN_KEY']
- xGM_ADMISSIONS_APPLICANT -> ['EXTERNAL_ID'] | ['PIDM_KEY', 'TERM_CODE_KEY', 'APPL_NO_KEY']
- GM_APPLICATION_CHECKLIST -> ['EXTERNAL_ID', 'ADMR_CODE_KEY']
- GM_FINANCIAL_HISTORY -> ['PIDM_KEY', 'TRANSACTION_ID']
- GM_PROGRAM_HISTORY_DETAIL -> ['PIDM_KEY', 'TERM_CODE_KEY']
- GM_STUDENT_DATA -> ['PIDM_KEY']
- GM_STUDENT_REGISTRATION_DETAIL -> ['PIDM_KEY', 'TERM_CODE_KEY', 'CRN_KEY'] *Only data for next year (20232, 202320, 20233, 20241)


In [1]:
import pandas as pd
from utils import Validator

In [2]:
validators = {}

## Hold Data

BT_HOLD_DATA -> ['PIDM_KEY', 'HOLD_TYPE', 'HOLD_FROM_DATE', 'HOLD_TO_DATE', 'HOLD_REASON', 'HOLD_USER']

In [3]:
baseline_filepath = "data/Prod/Baseline/BT_HOLD_DATA.csv"
validate_filepath = "data/Prod/Validate/Hold Data.csv"
column_mapping = [
    {"baseline_col_name": "PIDM_KEY",
     "baseline_col_type": "",
     "validate_col_name": "lang_pidmkey",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "ID",
     "baseline_col_type": "",
     "validate_col_name": "lang_id",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "HOLD_TYPE",
     "baseline_col_type": "",
     "validate_col_name": "lang_holdtype",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "HOLD_DESC",
     "baseline_col_type": "",
     "validate_col_name": "lang_holddescriptionorig",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "HOLD_FROM_DATE",
     "baseline_col_type": "",
     "validate_col_name": "lang_holdfromdate",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "HOLD_TO_DATE",
     "baseline_col_type": "",
     "validate_col_name": "lang_holdtodate",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "HOLD_REASON",
     "baseline_col_type": "",
     "validate_col_name": "lang_holdreason",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "HOLD_USER",
     "baseline_col_type": "",
     "validate_col_name": "lang_holduser",
     "validate_col_type": "",
     "common_col_type": "",
     },
]
baseline_date_cols = {"HOLD_FROM_DATE": None,  # "%d-%b-%y",
                      "HOLD_TO_DATE": None,}  # "%d-%b-%y",}
validate_date_cols = {"lang_holdfromdate": None,
                      "lang_holdtodate": None}
col_id = ['PIDM_KEY', 'HOLD_TYPE', 'HOLD_FROM_DATE', 'HOLD_TO_DATE', 'HOLD_REASON', 'HOLD_USER']
baseline_encoding = "utf-8"
validate_encoding = "utf-8"
# unify_text = False
# text_cols = None
unify_text = True
text_cols = ['HOLD_REASON']

In [4]:
cur_validator = Validator(baseline_filepath=baseline_filepath,
                          validate_filepath=validate_filepath,
                          column_mapping=column_mapping,
                          baseline_date_cols=baseline_date_cols,
                          validate_date_cols=validate_date_cols,
                          col_id=col_id,
                          baseline_encoding=baseline_encoding,
                          validate_encoding=validate_encoding,
                          unify_text=unify_text,
                          text_cols=text_cols,
                         )

C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:319: UserWarning:     Expected data type does not match origin data type. Validation    will force expected type if present, otherwise, real type.
  warnings.warn("    Expected data type does not match origin data type. Validation"
C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:326: UserWarning: Warning:
        Dataset Baseline
        
                Column: PIDM_KEY
                    Real Type: int64
                    Expected Type: NA
                Column: ID
                    Real Type: int64
                    Expected Type: NA
                Column: HOLD_TYPE
                    Real Type: object
                    Expected Type: NA
                Column: HOLD_DESC
                    Real Type: object
                    Expected Type: NA
                Column: HOLD_FROM

In [5]:
cur_validator.name_mapping

{'lang_pidmkey': 'PIDM_KEY',
 'lang_id': 'ID',
 'lang_holdtype': 'HOLD_TYPE',
 'lang_holddescriptionorig': 'HOLD_DESC',
 'lang_holdfromdate': 'HOLD_FROM_DATE',
 'lang_holdtodate': 'HOLD_TO_DATE',
 'lang_holdreason': 'HOLD_REASON',
 'lang_holduser': 'HOLD_USER'}

In [6]:
cur_validator.check_existence()

PIDM_KEY  HOLD_TYPE  HOLD_FROM_DATE  HOLD_TO_DATE  HOLD_REASON   
0         False      False           False         False        False  \
1         False      False           False         False        False   
2         False      False           False         False        False   
3         False      False           False         False        False   
4         False      False           False         False        False   
...         ...        ...             ...           ...          ...   
34760     False      False           False         False        False   
34761     False      False           False         False        False   
34762     False      False           False         False        False   
34763     False      False           False         False        False   
34764     False      False           False         False        False   

       HOLD_USER     ID  HOLD_DESC  
0          False   True       True  
1          False   True       True  
2          False   True       True  
3          False   True       True  
4          False   True       True  
...          ...    ...        ...  
34760      False   True       True  
34761      False  False      False  
34762      False   True       True  
34763      False   True       True  
34764      False   True       True  

[34765 rows x 8 columns]

In [7]:
cur_validator.existence_result.sum()

PIDM_KEY              0
HOLD_TYPE             0
HOLD_FROM_DATE        0
HOLD_TO_DATE          0
HOLD_REASON           0
HOLD_USER             0
ID                14034
HOLD_DESC         14034
dtype: int64

In [8]:
cur_validator.row_difference

25

In [9]:
cur_validator.col_difference

{'origin_cols_not_in_target': set(),
 'target_cols_not_in_origin': {'lang_holddescription', 'lang_student'}}

In [10]:
cur_validator.duplicated_rows

{'origin': 22, 'target': 22}

In [11]:
cur_validator.check_equality()

ID                           HOLD_DESC       
            origin target                       origin target
0      100001308.0    NaN  A&S Program Update Required    NaN
1      100001308.0    NaN  A&S Program Update Required    NaN
2      100001308.0    NaN  A&S Program Update Required    NaN
3      100002349.0    NaN  A&S Program Update Required    NaN
4       94347374.0    NaN  A&S Program Update Required    NaN
...            ...    ...                          ...    ...
34759  100420464.0    NaN                 Finance Hold    NaN
34760  100420472.0    NaN             International Ed    NaN
34762  100420807.0    NaN             International Ed    NaN
34763  100420844.0    NaN             International Ed    NaN
34764  100421643.0    NaN             International Ed    NaN

[14034 rows x 4 columns]

In [12]:
cur_validator.target_rows_not_in_origin

PIDM_KEY HOLD_TYPE HOLD_FROM_DATE HOLD_TO_DATE   
0      90001327        ZP     2019-06-08   2020-06-17  \
1      90001327        ZP     2020-02-01   2020-06-17   
2      90001327        ZP     2020-06-17   2020-06-17   
3      90002371        ZP     2020-02-11   1999-12-21   
4      90002871        ZP     2012-03-08   2012-06-22   
...         ...       ...            ...          ...   
14004  90594568        IE     2023-05-10   1999-12-31   
14005  90594609        FI     2023-04-18   1999-12-31   
14006  90594617        IE     2023-05-10   1999-12-31   
14007  90594963        IE     2023-04-28   1999-12-31   
14008  90595832        IE     2023-05-10   1999-12-31   

                         HOLD_REASON HOLD_USER  ID HOLD_DESC  
0                                NaN       NaN NaN       NaN  
1                                NaN       NaN NaN       NaN  
2                                NaN       NaN NaN       NaN  
3                                NaN       NaN NaN       NaN  
4                                NaN       NaN NaN       NaN  
...                              ...       ...  ..       ...  
14004       No proof of study permit    EIKARI NaN       NaN  
14005                EPBC Chargeback    MBERRY NaN       NaN  
14006       No proof of study permit    EIKARI NaN       NaN  
14007  Proof of Citizenship Required    LSALAS NaN       NaN  
14008       No proof of study permit    EIKARI NaN       NaN  

[14009 rows x 8 columns]

In [13]:
cur_validator.origin_rows_not_in_target

PIDM_KEY HOLD_TYPE HOLD_FROM_DATE        HOLD_TO_DATE   
0      90001327        ZP     2019-06-08 2020-06-17 11:38:10  \
1      90001327        ZP     2020-02-01 2020-06-17 11:38:10   
2      90001327        ZP     2020-06-17 2020-06-17 11:38:10   
3      90002371        ZP     2020-02-11                 NaT   
4      90002871        ZP     2012-03-08 2012-06-22 13:20:15   
...         ...       ...            ...                 ...   
14029  90594609        FI     2023-04-18 2099-12-31 00:00:00   
14030  90594617        IE     2023-05-10 2099-12-31 00:00:00   
14031  90594963        IE     2023-04-28 2099-12-31 00:00:00   
14032  90595001        IE     2023-05-15 2099-12-31 00:00:00   
14033  90595832        IE     2023-05-10 2099-12-31 00:00:00   

                         HOLD_REASON HOLD_USER  ID HOLD_DESC  
0                                NaN       NaN NaN       NaN  
1                                NaN       NaN NaN       NaN  
2                                NaN       NaN NaN       NaN  
3                                NaN       NaN NaN       NaN  
4                                NaN       NaN NaN       NaN  
...                              ...       ...  ..       ...  
14029                EPBC Chargeback    MBERRY NaN       NaN  
14030       No proof of study permit    EIKARI NaN       NaN  
14031  Proof of Citizenship Required    LSALAS NaN       NaN  
14032       No proof of study permit    EIKARI NaN       NaN  
14033       No proof of study permit    EIKARI NaN       NaN  

[14034 rows x 8 columns]

In [14]:
validators['hold_data'] = cur_validator

## Test Score

BT_TEST_SCORE -> ['PIDM_KEY', 'TEST_SCORE_CODE', 'TEST_SCORE_DATE']

In [15]:
baseline_filepath = "data/Prod/Baseline/BT_TEST_SCORE.csv"
validate_filepath = "data/Prod/Validate/Test Score.csv"
column_mapping = [
    {"baseline_col_name": "PIDM_KEY",
     "validate_col_name": "lang_pidmkey",
     "common_col_type": "",
     },
    {"baseline_col_name": "ID",
     "validate_col_name": "lang_id",
     "common_col_type": "",
     },
    {"baseline_col_name": "TEST_SCORE_CODE",
     "validate_col_name": "lang_testscorecode",
     "common_col_type": "",
     },
    {"baseline_col_name": "TEST_SCORE_CODE_DESC",
     "validate_col_name": "lang_testscorecodedescriptionorig",
     "common_col_type": "",
     },
    {"baseline_col_name": "TEST_SCORE",
     "validate_col_name": "lang_testscore",
     "common_col_type": "",
     },
    {"baseline_col_name": "TEST_SCORE_DATE",
     "validate_col_name": "lang_testscoredate",
     "common_col_type": "",
     },
    {"baseline_col_name": "TEST_SCORE_TERM",
     "validate_col_name": "lang_testscoreterm",
     "common_col_type": "",
     },
]
baseline_date_cols = {"TEST_SCORE_DATE": None}
validate_date_cols = {"lang_testscoredate": None}
col_id = ['PIDM_KEY', 'TEST_SCORE_CODE', 'TEST_SCORE_DATE']
baseline_encoding = "utf-8"
validate_encoding = "utf-8"
# unify_text = False
# text_cols = None
unify_text = False
text_cols = None

In [16]:
cur_validator = Validator(baseline_filepath=baseline_filepath,
                          validate_filepath=validate_filepath,
                          column_mapping=column_mapping,
                          baseline_date_cols=baseline_date_cols,
                          validate_date_cols=validate_date_cols,
                          col_id=col_id,
                          baseline_encoding=baseline_encoding,
                          validate_encoding=validate_encoding,
                          unify_text=unify_text,
                          text_cols=text_cols,
                         )

C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:319: UserWarning:     Expected data type does not match origin data type. Validation    will force expected type if present, otherwise, real type.
  warnings.warn("    Expected data type does not match origin data type. Validation"
C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:326: UserWarning: Warning:
        Dataset Baseline
        
                Column: PIDM_KEY
                    Real Type: int64
                    Expected Type: NA
                Column: ID
                    Real Type: int64
                    Expected Type: NA
                Column: TEST_SCORE_CODE
                    Real Type: object
                    Expected Type: NA
                Column: TEST_SCORE_CODE_DESC
                    Real Type: object
                    Expected Type: NA
                

In [17]:
cur_validator.name_mapping

{'lang_pidmkey': 'PIDM_KEY',
 'lang_id': 'ID',
 'lang_testscorecode': 'TEST_SCORE_CODE',
 'lang_testscorecodedescriptionorig': 'TEST_SCORE_CODE_DESC',
 'lang_testscore': 'TEST_SCORE',
 'lang_testscoredate': 'TEST_SCORE_DATE',
 'lang_testscoreterm': 'TEST_SCORE_TERM'}

In [18]:
cur_validator.check_existence()

PIDM_KEY  TEST_SCORE_CODE  TEST_SCORE_DATE     ID   
0          False            False            False  False  \
1          False            False            False  False   
2          False            False            False  False   
3          False            False            False  False   
4          False            False            False  False   
...          ...              ...              ...    ...   
706510     False            False            False   True   
706511     False            False            False   True   
706512     False            False            False   True   
706513     False            False            False   True   
706514     False            False            False   True   

        TEST_SCORE_CODE_DESC  TEST_SCORE  TEST_SCORE_TERM  
0                      False       False            False  
1                      False       False            False  
2                      False       False            False  
3                      False       False            False  
4                      False       False            False  
...                      ...         ...              ...  
706510                  True        True             True  
706511                  True        True             True  
706512                  True        True             True  
706513                  True        True             True  
706514                  True        True             True  

[706515 rows x 7 columns]

In [19]:
cur_validator.existence_result.sum()

PIDM_KEY                  0
TEST_SCORE_CODE           0
TEST_SCORE_DATE           0
ID                      503
TEST_SCORE_CODE_DESC    503
TEST_SCORE              503
TEST_SCORE_TERM         503
dtype: int64

In [20]:
cur_validator.row_difference

432

In [21]:
cur_validator.col_difference

{'origin_cols_not_in_target': set(),
 'target_cols_not_in_origin': {'lang_student',
  'lang_testscorecodedescription'}}

In [22]:
cur_validator.duplicated_rows

{'origin': 0, 'target': 0}

In [23]:
cur_validator.check_equality()

ID          TEST_SCORE_CODE_DESC        TEST_SCORE          
             origin target                 origin target     origin target   
5113    100033857.0    NaN     LPI - Exempt Essay    NaN       25.0    NaN  \
6701    100056898.0    NaN   Langara English Test    NaN        1.0    NaN   
6702    100056898.0    NaN   Langara English Test    NaN        2.0    NaN   
6703    100056898.0    NaN   Langara English Test    NaN        1.0    NaN   
42076   100202282.0    NaN             Biology 12    NaN       75.0    NaN   
...             ...    ...                    ...    ...        ...    ...   
706510  100422199.0    NaN             Physics 11    NaN       65.0    NaN   
706511  100422199.0    NaN             Physics 12    NaN       62.0    NaN   
706512  100422199.0    NaN         Precalculus 11    NaN       60.0    NaN   
706513  100422199.0    NaN         Precalculus 12    NaN       61.0    NaN   
706514  100422214.0    NaN  Duolingo English Test    NaN      110.0    NaN   

       TEST_SCORE_TERM         
                origin target  
5113          199410.0    NaN  
6701          200210.0    NaN  
6702          200310.0    NaN  
6703          200320.0    NaN  
42076         202320.0    NaN  
...                ...    ...  
706510        202220.0    NaN  
706511        202320.0    NaN  
706512        202220.0    NaN  
706513        202320.0    NaN  
706514        202320.0    NaN  

[514 rows x 8 columns]

In [24]:
cur_validator.target_rows_not_in_origin

PIDM_KEY TEST_SCORE_CODE TEST_SCORE_DATE  ID TEST_SCORE_CODE_DESC   
0   90415869            BIO2      2012-06-01 NaN                  NaN  \
1   90415869            CHE1      2011-06-01 NaN                  NaN   
2   90415869            CHE2      2012-06-01 NaN                  NaN   
3   90415869            ENG2      2012-06-01 NaN                  NaN   
4   90415869            MAT1      2011-06-01 NaN                  NaN   
..       ...             ...             ...  ..                  ...   
66  90590078            IELW      2022-11-26 NaN                  NaN   
67  90591064            IELL      2022-11-12 NaN                  NaN   
68  90591064            IELS      2022-11-12 NaN                  NaN   
69  90591064            IELT      2022-11-12 NaN                  NaN   
70  90591064            IELW      2022-11-12 NaN                  NaN   

    TEST_SCORE  TEST_SCORE_TERM  
0          NaN              NaN  
1          NaN              NaN  
2          NaN              NaN  
3          NaN              NaN  
4          NaN              NaN  
..         ...              ...  
66         NaN              NaN  
67         NaN              NaN  
68         NaN              NaN  
69         NaN              NaN  
70         NaN              NaN  

[71 rows x 7 columns]

In [25]:
cur_validator.origin_rows_not_in_target

PIDM_KEY TEST_SCORE_CODE TEST_SCORE_DATE  ID TEST_SCORE_CODE_DESC   
0    90155137            LPXE      1994-02-01 NaN                  NaN  \
1    90178185             LET      2002-03-23 NaN                  NaN   
2    90178185             LET      2003-04-05 NaN                  NaN   
3    90178185             LET      2003-05-24 NaN                  NaN   
4    90361514            BIO2      2023-06-01 NaN                  NaN   
..        ...             ...             ...  ..                  ...   
498  90596409            PHY1      2022-06-01 NaN                  NaN   
499  90596409            PHY2      2023-06-01 NaN                  NaN   
500  90596409            PRC1      2022-06-01 NaN                  NaN   
501  90596409            PRC2      2023-06-01 NaN                  NaN   
502  90596424            DUOL      2023-05-10 NaN                  NaN   

     TEST_SCORE  TEST_SCORE_TERM  
0           NaN              NaN  
1           NaN              NaN  
2           NaN              NaN  
3           NaN              NaN  
4           NaN              NaN  
..          ...              ...  
498         NaN              NaN  
499         NaN              NaN  
500         NaN              NaN  
501         NaN              NaN  
502         NaN              NaN  

[503 rows x 7 columns]

In [26]:
validators['test_score'] = cur_validator

## Academic History

BT_ACADEMIC_HISTORY_DETAIL -> ['PIDM_KEY', 'TERM_CODE_KEY', 'CRN_KEY']

In [51]:
baseline_filepath = "data/Prod/Baseline/BT_ACADEMIC_HISTORY_DETAIL.csv"
validate_filepath = "data/Prod/Validate/Course History.csv"
column_mapping = [
    {"baseline_col_name": "PIDM_KEY",
     "validate_col_name": "lang_pidmkey",
     "common_col_type": "",
     },
    {"baseline_col_name": "TERM_CODE_KEY",
     "validate_col_name": "lang_termcodekey",
     "common_col_type": "",
     },
    {"baseline_col_name": "CRN_KEY",
     "validate_col_name": "lang_crnkey",
     "common_col_type": "string",
     },
    {"baseline_col_name": "ID",
     "validate_col_name": "lang_id",
     "common_col_type": "",
     },
    {"baseline_col_name": "SUBJ_CODE",
     "validate_col_name": "lang_subjectcode",
     "common_col_type": "",
     },
    {"baseline_col_name": "COURSE_NUMBER",
     "validate_col_name": "lang_coursenumber",
     "common_col_type": "string",
     },
    {"baseline_col_name": "COURSE_TITLE",
     "validate_col_name": "lang_coursetitleorig",
     "common_col_type": "",
     },
    {"baseline_col_name": "GRADE_CODE",
     "validate_col_name": "lang_gradecode",
     "common_col_type": "",
     },
    {"baseline_col_name": "CREDIT_HOURS",
     "validate_col_name": "mshied_creditsearrned",
     "common_col_type": "",
     },
    {"baseline_col_name": "REPEAT_COURSE_IND",
     "validate_col_name": "lang_repeatcourseind",
     "common_col_type": "",
     },
]
baseline_date_cols = None # {"TEST_SCORE_DATE": "%d-%b-%y"}
validate_date_cols = None # {"lang_testscoredate": None}
col_id = ['PIDM_KEY', 'TERM_CODE_KEY', 'CRN_KEY']
baseline_encoding = "utf-8"
validate_encoding = "utf-8"
# unify_text = False
# text_cols = None
unify_text = False
text_cols = None

In [52]:
cur_validator = Validator(baseline_filepath=baseline_filepath,
                          validate_filepath=validate_filepath,
                          column_mapping=column_mapping,
                          baseline_date_cols=baseline_date_cols,
                          validate_date_cols=validate_date_cols,
                          col_id=col_id,
                          baseline_encoding=baseline_encoding,
                          validate_encoding=validate_encoding,
                          unify_text=unify_text,
                          text_cols=text_cols,
                         )

C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:36: DtypeWarning: Columns (2,5) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(filepath, encoding=encoding)
C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:36: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(filepath, encoding=encoding)
C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:319: UserWarning:     Expected data type does not match origin data type. Validation    will force expected type if present, otherwise, real type.
  warnings.warn("    Expected data type does not match origin data type. Validation"
C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analy

In [53]:
cur_validator.name_mapping

{'lang_pidmkey': 'PIDM_KEY',
 'lang_termcodekey': 'TERM_CODE_KEY',
 'lang_crnkey': 'CRN_KEY',
 'lang_id': 'ID',
 'lang_subjectcode': 'SUBJ_CODE',
 'lang_coursenumber': 'COURSE_NUMBER',
 'lang_coursetitleorig': 'COURSE_TITLE',
 'lang_gradecode': 'GRADE_CODE',
 'mshied_creditsearrned': 'CREDIT_HOURS',
 'lang_repeatcourseind': 'REPEAT_COURSE_IND'}

In [54]:
cur_validator.check_existence()

PIDM_KEY  TERM_CODE_KEY  CRN_KEY     ID  SUBJ_CODE  COURSE_NUMBER   
0          False          False    False  False      False          False  \
1          False          False    False  False      False          False   
2          False          False    False  False      False          False   
3          False          False    False  False      False          False   
4          False          False    False  False      False          False   
...          ...            ...      ...    ...        ...            ...   
746484     False          False    False  False      False          False   
746485     False          False    False  False      False          False   
746486     False          False    False  False      False          False   
746487     False          False    False  False      False          False   
746488     False          False    False  False      False          False   

        COURSE_TITLE  GRADE_CODE  CREDIT_HOURS  REPEAT_COURSE_IND  
0              False       False         False              False  
1              False       False         False              False  
2              False       False         False              False  
3              False       False         False              False  
4              False       False         False              False  
...              ...         ...           ...                ...  
746484         False       False         False              False  
746485         False       False         False              False  
746486         False       False         False              False  
746487         False       False         False              False  
746488         False       False         False              False  

[746489 rows x 10 columns]

In [55]:
cur_validator.existence_result.sum()

PIDM_KEY              0
TERM_CODE_KEY         0
CRN_KEY               0
ID                   55
SUBJ_CODE            55
COURSE_NUMBER        55
COURSE_TITLE         55
GRADE_CODE           55
CREDIT_HOURS         55
REPEAT_COURSE_IND     0
dtype: int64

In [56]:
cur_validator.row_difference

1

In [57]:
cur_validator.col_difference

{'origin_cols_not_in_target': set(),
 'target_cols_not_in_origin': {'lang_subjectdescription',
  'lang_subjectdescriptionorig',
  'lang_termdescriptionorig',
  'mshied_academicperiodid',
  'mshied_courseid',
  'mshied_studentid'}}

In [58]:
cur_validator.duplicated_rows

{'origin': 0, 'target': 20}

In [59]:
cur_validator.check_equality()

ID        SUBJ_CODE        COURSE_NUMBER          
             origin target    origin target        origin target   
5528     84310796.0    NaN      ASSC    NaN          2075   <NA>  \
9162            NaN    NaN       NaN    NaN          <NA>   <NA>   
12438           NaN    NaN       NaN    NaN          <NA>   <NA>   
18836   100033857.0    NaN      JOUR    NaN          1147   <NA>   
18837   100033857.0    NaN      JOUR    NaN          1168   <NA>   
...             ...    ...       ...    ...           ...    ...   
742445          NaN    NaN       NaN    NaN          <NA>   <NA>   
742843  100406462.0    NaN      CSFW    NaN          1004   <NA>   
743983  100407397.0    NaN      CSFW    NaN          1004   <NA>   
746063  100415774.0    NaN      CSFW    NaN          1004   <NA>   
746204  100416990.0    NaN      CSFW    NaN          1004   <NA>   

                       COURSE_TITLE        GRADE_CODE        CREDIT_HOURS   
                             origin target     origin target       origin   
5528          ExA: Onsite Practicum    NaN          S    NaN         30.0  \
9162                            NaN    NaN          A     IP          NaN   
12438                           NaN    NaN          A     IP          NaN   
18836              Editing & Design    NaN         A-    NaN          3.0   
18837              Photo Journalism    NaN         B+    NaN          2.0   
...                             ...    ...        ...    ...          ...   
742445                          NaN    NaN          B      I          NaN   
742843  Sage 300-1 ACCPAC 1- Online    NaN         A-    NaN          1.8   
743983  Sage 300-1 ACCPAC 1- Online    NaN          N    NaN          1.8   
746063  Sage 300-1 ACCPAC 1- Online    NaN          A    NaN          1.8   
746204  Sage 300-1 ACCPAC 1- Online    NaN          A    NaN          1.8   

              REPEAT_COURSE_IND         
       target            origin target  
5528      NaN               NaN    NaN  
9162      NaN               NaN    NaN  
12438     NaN               NaN    NaN  
18836     NaN               NaN    NaN  
18837     NaN               NaN    NaN  
...       ...               ...    ...  
742445    NaN               NaN    NaN  
742843    NaN               NaN    NaN  
743983    NaN               NaN    NaN  
746063    NaN               NaN    NaN  
746204    NaN               NaN    NaN  

[101 rows x 14 columns]

In [62]:
validators['academic_history'] = cur_validator

## Admissions Applicant
- GM_ADMISSIONS_APPLICANT -> ['EXTERNAL_ID'] | ['PIDM_KEY', 'TERM_CODE_KEY', 'APPL_NO_KEY']


In [81]:
baseline_filepath = "data/Prod/Baseline/BT_ADMISSIONS_APPLICANT.csv"
validate_filepath = "data/Prod/Validate/Admissions Applicant (Custom).csv"
column_mapping = [
    {"baseline_col_name": "EXTERNAL_ID",
     "validate_col_name": "lang_externalid",
     "common_col_type": "",
     },
    # {"baseline_col_name": "PIDM_KEY",
    #  "validate_col_name": "",
    #  "common_col_type": "",
    #  },
    {"baseline_col_name": "TERM_CODE_KEY",
     "validate_col_name": "lang_termcodekey",
     "common_col_type": "",
     },
    {"baseline_col_name": "TERM_DESC",
     "validate_col_name": "lang_termdescriptionorig",
     "common_col_type": "",
     },
    {"baseline_col_name": "APPL_NO_KEY",
     "validate_col_name": "lang_applicationnumberkey",
     "common_col_type": "",
     },
    {"baseline_col_name": "COMPLETE_IND",
     "validate_col_name": "lang_completeind",
     "common_col_type": "",
     },
    {"baseline_col_name": "INCOMPLETE_IND",
     "validate_col_name": "lang_incompleteind",
     "common_col_type": "",
     },
    {"baseline_col_name": "ID",
     "validate_col_name": "lang_id",
     "common_col_type": "string",
     },
    {"baseline_col_name": "APPLICATION_DATE",
     "validate_col_name": "lang_applicationdate",
     "common_col_type": "",
     },
    {"baseline_col_name": "ADMT_CODE",
     "validate_col_name": "lang_admtcode",
     "common_col_type": "",
     },
    {"baseline_col_name": "ADMT_DESC",
     "validate_col_name": "lang_admtdescriptionorig",
     "common_col_type": "",
     },
    {"baseline_col_name": "PROGRAM_CODE",
     "validate_col_name": "lang_programcode",
     "common_col_type": "",
     },
    {"baseline_col_name": "PROGRAM_DESC1",
     "validate_col_name": "lang_programnameorig",
     "common_col_type": "",
     },
    {"baseline_col_name": "MAJOR",
     "validate_col_name": "lang_major",
     "common_col_type": "",
     },
    {"baseline_col_name": "CONCENTRATION",
     "validate_col_name": "lang_concentration",
     "common_col_type": "",
     },
    {"baseline_col_name": "APDC_CODE1",
     "validate_col_name": "lang_apdccode1",
     "common_col_type": "",
     },
    {"baseline_col_name": "APDC_DESC1",
     "validate_col_name": "lang_apdcdescriptionorig",
     "common_col_type": "",
     },
    {"baseline_col_name": "APDC_DECISION_DATE1",
     "validate_col_name": "lang_apdcdecisiondate1",
     "common_col_type": "",
     },
    {"baseline_col_name": "INTERNATIONAL_LEGAL_NATION",
     "validate_col_name": "lang_internationallegalnation",
     "common_col_type": "",
     },
    {"baseline_col_name": "RESD_CODE",
     "validate_col_name": "lang_residentcode",
     "common_col_type": "",
     },
    {"baseline_col_name": "RESD_DESC",
     "validate_col_name": "lang_residentdescriptionorig",
     "common_col_type": "",
     },
    {"baseline_col_name": "STUDENT_TYPE",
     "validate_col_name": "lang_studenttype",
     "common_col_type": "",
     },
    {"baseline_col_name": "PGM_TYPE",
     "validate_col_name": "lang_pgmtype",
     "common_col_type": "",
     },
    {"baseline_col_name": "PGM_TYPE_DESC",
     "validate_col_name": "lang_pgmtypedescriptionorig",
     "common_col_type": "",
     },
    # {"baseline_col_name": "XML_DOC_ID",
    #  "validate_col_name": "",
    #  "common_col_type": "",
    #  },
    # {"baseline_col_name": "WEB_ID",
    #  "validate_col_name": "",
    #  "common_col_type": "",
    #  },
]
baseline_date_cols = {"APPLICATION_DATE": None,  # "%d-%b-%y",
                      "APDC_DECISION_DATE1": None,}  # "%d-%b-%y",}
validate_date_cols = {"lang_applicationdate": None,
                      "lang_apdcdecisiondate1": None}
col_id = ['EXTERNAL_ID']
baseline_encoding = "utf-8"
validate_encoding = "utf-8"
unify_text = False
text_cols = None
# unify_text = True
# text_cols = ['HOLD_REASON']

In [82]:
cur_validator = Validator(baseline_filepath=baseline_filepath,
                          validate_filepath=validate_filepath,
                          column_mapping=column_mapping,
                          baseline_date_cols=baseline_date_cols,
                          validate_date_cols=validate_date_cols,
                          col_id=col_id,
                          baseline_encoding=baseline_encoding,
                          validate_encoding=validate_encoding,
                          unify_text=unify_text,
                          text_cols=text_cols,
                         )

C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:36: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(filepath, encoding=encoding)
C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:36: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(filepath, encoding=encoding)
C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:319: UserWarning:     Expected data type does not match origin data type. Validation    will force expected type if present, otherwise, real type.
  warnings.warn("    Expected data type does not match origin data type. Validation"
C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\

In [83]:
cur_validator.name_mapping

{'lang_externalid': 'EXTERNAL_ID',
 'lang_termcodekey': 'TERM_CODE_KEY',
 'lang_termdescriptionorig': 'TERM_DESC',
 'lang_applicationnumberkey': 'APPL_NO_KEY',
 'lang_completeind': 'COMPLETE_IND',
 'lang_incompleteind': 'INCOMPLETE_IND',
 'lang_id': 'ID',
 'lang_applicationdate': 'APPLICATION_DATE',
 'lang_admtcode': 'ADMT_CODE',
 'lang_admtdescriptionorig': 'ADMT_DESC',
 'lang_programcode': 'PROGRAM_CODE',
 'lang_programnameorig': 'PROGRAM_DESC1',
 'lang_major': 'MAJOR',
 'lang_concentration': 'CONCENTRATION',
 'lang_apdccode1': 'APDC_CODE1',
 'lang_apdcdescriptionorig': 'APDC_DESC1',
 'lang_apdcdecisiondate1': 'APDC_DECISION_DATE1',
 'lang_internationallegalnation': 'INTERNATIONAL_LEGAL_NATION',
 'lang_residentcode': 'RESD_CODE',
 'lang_residentdescriptionorig': 'RESD_DESC',
 'lang_studenttype': 'STUDENT_TYPE',
 'lang_pgmtype': 'PGM_TYPE',
 'lang_pgmtypedescriptionorig': 'PGM_TYPE_DESC'}

In [84]:
cur_validator.check_existence()

EXTERNAL_ID  TERM_CODE_KEY  TERM_DESC  APPL_NO_KEY  COMPLETE_IND   
0             False          False      False        False         False  \
1             False          False      False        False         False   
2             False          False      False        False         False   
3             False          False      False        False         False   
4             False          False      False        False         False   
...             ...            ...        ...          ...           ...   
213749        False          False      False        False         False   
213750        False          False      False        False         False   
213751        False          False      False        False         False   
213752        False          False      False        False         False   
213753        False          False      False        False         False   

        INCOMPLETE_IND     ID  APPLICATION_DATE  ADMT_CODE  ADMT_DESC   
0                False  False             False      False      False  \
1                False  False             False      False      False   
2                False  False             False      False      False   
3                False  False             False      False      False   
4                False  False             False      False      False   
...                ...    ...               ...        ...        ...   
213749           False  False             False      False      False   
213750           False  False             False      False      False   
213751           False  False             False      False      False   
213752           False  False             False      False      False   
213753           False  False             False      False      False   

        PROGRAM_CODE  PROGRAM_DESC1  MAJOR  CONCENTRATION  APDC_CODE1   
0              False          False  False          False       False  \
1              False          False  False          False       False   
2              False          False  False          False       False   
3              False          False  False          False       False   
4              False          False  False          False       False   
...              ...            ...    ...            ...         ...   
213749         False          False  False          False       False   
213750         False          False  False          False       False   
213751         False          False  False          False       False   
213752         False          False  False          False       False   
213753         False          False  False          False       False   

        APDC_DESC1  APDC_DECISION_DATE1  INTERNATIONAL_LEGAL_NATION   
0            False                False                       False  \
1            False                False                       False   
2            False                False                       False   
3            False                False                       False   
4            False                False                       False   
...            ...                  ...                         ...   
213749       False                False                       False   
213750       False                False                       False   
213751       False                False                       False   
213752       False                False                       False   
213753       False                False                       False   

        RESD_CODE  RESD_DESC  STUDENT_TYPE  PGM_TYPE  PGM_TYPE_DESC  
0           False      False         False     False          False  
1           False      False         False     False          False  
2           False      False         False     False          False  
3           False      False         False     False          False  
4           False      False         False     False          False  
...           ...        ...           ...       ...            ... 

In [85]:
cur_validator.existence_result.sum()

EXTERNAL_ID                     0
TERM_CODE_KEY                 257
TERM_DESC                     257
APPL_NO_KEY                   257
COMPLETE_IND                  257
INCOMPLETE_IND                257
ID                            257
APPLICATION_DATE              257
ADMT_CODE                     257
ADMT_DESC                     257
PROGRAM_CODE                  257
PROGRAM_DESC1                 254
MAJOR                         257
CONCENTRATION                   7
APDC_CODE1                    257
APDC_DESC1                    257
APDC_DECISION_DATE1           257
INTERNATIONAL_LEGAL_NATION    251
RESD_CODE                     257
RESD_DESC                     257
STUDENT_TYPE                  257
PGM_TYPE                      252
PGM_TYPE_DESC                 252
dtype: int64

In [86]:
cur_validator.row_difference

254

In [87]:
cur_validator.col_difference

{'origin_cols_not_in_target': {'PIDM_KEY', 'WEB_ID', 'XML_DOC_ID'},
 'target_cols_not_in_origin': {'bsi_admtdescription',
  'bsi_apdcdescription',
  'bsi_applicant',
  'bsi_programdescription',
  'bsi_residentdescription',
  'bsi_termdescription',
  'lang_id.1'}}

In [88]:
cur_validator.duplicated_rows

{'origin': 0, 'target': 0}

In [89]:
cur_validator.check_equality()

TERM_CODE_KEY        TERM_DESC        APPL_NO_KEY        COMPLETE_IND   
              origin target    origin target      origin target       origin   
0                NaN    NaN       NaN    NaN         NaN    NaN          NaN  \
1                NaN    NaN       NaN    NaN         NaN    NaN          NaN   
2                NaN    NaN       NaN    NaN         NaN    NaN          NaN   
3                NaN    NaN       NaN    NaN         NaN    NaN          NaN   
4                NaN    NaN       NaN    NaN         NaN    NaN          NaN   
...              ...    ...       ...    ...         ...    ...          ...   
213749           NaN    NaN       NaN    NaN         NaN    NaN          NaN   
213750           NaN    NaN       NaN    NaN         NaN    NaN          NaN   
213751           NaN    NaN       NaN    NaN         NaN    NaN          NaN   
213752           NaN    NaN       NaN    NaN         NaN    NaN          NaN   
213753           NaN    NaN       NaN    NaN         NaN    NaN          NaN   

              INCOMPLETE_IND                ID              APPLICATION_DATE   
       target         origin target     origin    target              origin   
0         NaN            NaN    NaN  100001308  90001327 2018-09-19 08:05:40  \
1         NaN            NaN    NaN   80216112  90001653                 NaT   
2         NaN            NaN    NaN  100002349  90002371                 NaT   
3         NaN            NaN    NaN   94347374  90002871                 NaT   
4         NaN            NaN    NaN   96340872  90004491 2019-04-03 13:25:13   
...       ...            ...    ...        ...       ...                 ...   
213749    NaN            NaN    NaN  100378150  90551700 2023-04-25 08:52:53   
213750    NaN            NaN    NaN  100383000  90556586                 NaT   
213751    NaN            NaN    NaN  100394663  90568446 2023-01-23 09:31:50   
213752    NaN            NaN    NaN  100394663  90568446 2023-04-24 09:20:53   
213753    NaN            NaN    NaN  100394663  90568446 2023-04-24 09:20:53   

                  ADMT_CODE        ADMT_DESC        PROGRAM_CODE          
           target    origin target    origin target       origin target   
0      2018-09-19       NaN    NaN       NaN    NaN          NaN    NaN  \
1             NaT       NaN    NaN       NaN    NaN          NaN    NaN   
2             NaT       NaN    NaN       NaN    NaN          NaN    NaN   
3             NaT       NaN    NaN       NaN    NaN          NaN    NaN   
4      2019-04-03       NaN    NaN       NaN    NaN          NaN    NaN   
...           ...       ...    ...       ...    ...          ...    ...   
213749 2023-04-25       NaN    NaN       NaN    NaN          NaN    NaN   
213750        NaT       NaN    NaN       NaN    NaN          NaN    NaN   
213751 2023-01-23       NaN    NaN       NaN    NaN          NaN    NaN   
213752 2023-04-24       NaN    NaN       NaN    NaN          NaN    NaN   
213753 2023-04-24       NaN    NaN       NaN    NaN          NaN    NaN   

       PROGRAM_DESC1         MAJOR        CONCENTRATION        APDC_CODE1   
              origin target origin target        origin target     origin   
0                NaN    NaN    NaN    NaN           NaN    NaN        NaN  \
1                NaN    NaN    NaN    NaN           NaN    NaN        NaN   
2                NaN    NaN    NaN    NaN           NaN    NaN        NaN   
3                NaN    NaN    NaN    NaN           NaN    NaN        NaN   
4                NaN    NaN    NaN    NaN           NaN    NaN        NaN   
...              ...    ...    ...    ...           ...    ...        ...   
213749           NaN    NaN    NaN    NaN           NaN    NaN        NaN   
213750           NaN    NaN    NaN    NaN           NaN    NaN        NaN   
213751           NaN    NaN    NaN    NaN           NaN    NaN        NaN   
213752           NaN    NaN    NaN    NaN           NaN    NaN        NaN   
213753           NaN    N

In [99]:
cur_validator.origin_data_for_validation[cur_validator.origin_data_for_validation['EXTERNAL_ID'] == 900013272019101]

EXTERNAL_ID  TERM_CODE_KEY    TERM_DESC  APPL_NO_KEY COMPLETE_IND   
0  900013272019101       201910.0  Spring 2019          1.0            N  \

  INCOMPLETE_IND         ID    APPLICATION_DATE ADMT_CODE   
0              N  100001308 2018-09-19 08:05:40        DA  \

                        ADMT_DESC PROGRAM_CODE   
0  Dean's Admission (19 and over)      CR_ABST  \

                                 PROGRAM_DESC1 MAJOR CONCENTRATION APDC_CODE1   
0  Certificate: Aboriginal Studies Post Degree  ABST           NaN         AA  \

           APDC_DESC1 APDC_DECISION_DATE1  INTERNATIONAL_LEGAL_NATION   
0  Applicant Accepted 2018-10-01 12:41:21                       156.0  \

  RESD_CODE RESD_DESC STUDENT_TYPE PGM_TYPE   PGM_TYPE_DESC  
0         R  Resident            1       OE  Open Enrolment

In [100]:
cur_validator.target_data_for_validation[cur_validator.target_data_for_validation['EXTERNAL_ID'] == 900013272019101]

EXTERNAL_ID  TERM_CODE_KEY    TERM_DESC  APPL_NO_KEY COMPLETE_IND   
0  900013272019101       201910.0  Spring 2019          1.0            N  \

  INCOMPLETE_IND        ID APPLICATION_DATE ADMT_CODE   
0              N  90001327       2018-09-19        DA  \

                        ADMT_DESC PROGRAM_CODE   
0  Dean's Admission (19 and over)      CR_ABST  \

                                 PROGRAM_DESC1 MAJOR CONCENTRATION APDC_CODE1   
0  Certificate: Aboriginal Studies Post Degree  ABST           NaN         AA  \

           APDC_DESC1 APDC_DECISION_DATE1  INTERNATIONAL_LEGAL_NATION   
0  Applicant Accepted          2018-10-01                       156.0  \

  RESD_CODE RESD_DESC STUDENT_TYPE PGM_TYPE   PGM_TYPE_DESC  
0         R  Resident            1       OE  Open Enrolment

In [90]:
cur_validator.target_rows_not_in_origin

EXTERNAL_ID  TERM_CODE_KEY TERM_DESC  APPL_NO_KEY COMPLETE_IND   
0  904158692014201            NaN       NaN          NaN          NaN  \
1  904158692015203            NaN       NaN          NaN          NaN   
2  904158692015302            NaN       NaN          NaN          NaN   

  INCOMPLETE_IND    ID APPLICATION_DATE ADMT_CODE ADMT_DESC PROGRAM_CODE   
0            NaN  <NA>              NaT       NaN       NaN          NaN  \
1            NaN  <NA>              NaT       NaN       NaN          NaN   
2            NaN  <NA>              NaT       NaN       NaN          NaN   

  PROGRAM_DESC1 MAJOR CONCENTRATION APDC_CODE1 APDC_DESC1 APDC_DECISION_DATE1   
0           NaN   NaN           NaN        NaN        NaN                 NaT  \
1           NaN   NaN           NaN        NaN        NaN                 NaT   
2           NaN   NaN           NaN        NaN        NaN                 NaT   

   INTERNATIONAL_LEGAL_NATION RESD_CODE RESD_DESC STUDENT_TYPE PGM_TYPE   
0                         NaN       NaN       NaN          NaN      NaN  \
1                         NaN       NaN       NaN          NaN      NaN   
2                         NaN       NaN       NaN          NaN      NaN   

  PGM_TYPE_DESC  
0           NaN  
1           NaN  
2           NaN

In [91]:
cur_validator.origin_rows_not_in_target

EXTERNAL_ID  TERM_CODE_KEY TERM_DESC  APPL_NO_KEY COMPLETE_IND   
0     900922142023308            NaN       NaN          NaN          NaN  \
1     901551372001301            NaN       NaN          NaN          NaN   
2     901781852002201            NaN       NaN          NaN          NaN   
3     901781852002302            NaN       NaN          NaN          NaN   
4     901831372023306            NaN       NaN          NaN          NaN   
..                ...            ...       ...          ...          ...   
252   905964292024102            NaN       NaN          NaN          NaN   
253   905964302024101            NaN       NaN          NaN          NaN   
254   905964312024101            NaN       NaN          NaN          NaN   
255  9045233820241010            NaN       NaN          NaN          NaN   
256  9046723420233013            NaN       NaN          NaN          NaN   

    INCOMPLETE_IND    ID APPLICATION_DATE ADMT_CODE ADMT_DESC PROGRAM_CODE   
0              NaN  <NA>              NaT       NaN       NaN          NaN  \
1              NaN  <NA>              NaT       NaN       NaN          NaN   
2              NaN  <NA>              NaT       NaN       NaN          NaN   
3              NaN  <NA>              NaT       NaN       NaN          NaN   
4              NaN  <NA>              NaT       NaN       NaN          NaN   
..             ...   ...              ...       ...       ...          ...   
252            NaN  <NA>              NaT       NaN       NaN          NaN   
253            NaN  <NA>              NaT       NaN       NaN          NaN   
254            NaN  <NA>              NaT       NaN       NaN          NaN   
255            NaN  <NA>              NaT       NaN       NaN          NaN   
256            NaN  <NA>              NaT       NaN       NaN          NaN   

    PROGRAM_DESC1 MAJOR CONCENTRATION APDC_CODE1 APDC_DESC1   
0             NaN   NaN           NaN        NaN        NaN  \
1             NaN   NaN           NaN        NaN        NaN   
2             NaN   NaN           NaN        NaN        NaN   
3             NaN   NaN           NaN        NaN        NaN   
4             NaN   NaN           NaN        NaN        NaN   
..            ...   ...           ...        ...        ...   
252           NaN   NaN           NaN        NaN        NaN   
253           NaN   NaN           NaN        NaN        NaN   
254           NaN   NaN           NaN        NaN        NaN   
255           NaN   NaN           NaN        NaN        NaN   
256           NaN   NaN           NaN        NaN        NaN   

    APDC_DECISION_DATE1  INTERNATIONAL_LEGAL_NATION RESD_CODE RESD_DESC   
0                   NaT                         NaN       NaN       NaN  \
1                   NaT                         NaN       NaN       NaN   
2                   NaT                         NaN       NaN       NaN   
3                   NaT                         NaN       NaN       NaN   
4                   NaT                         NaN       NaN       NaN   
..                  ...                         ...       ...       ...   
252                 NaT                         NaN       NaN       NaN   
253                 NaT                         NaN       NaN       NaN   
254                 NaT                         NaN       NaN       NaN   
255                 NaT                         NaN       NaN       NaN   
256                 NaT                         NaN       NaN       NaN   

    STUDENT_TYPE PGM_TYPE PGM_TYPE_DESC  
0            NaN      NaN           NaN  
1            NaN      NaN           NaN  
2            NaN      NaN           NaN  
3            NaN      NaN           NaN  
4            NaN      NaN           NaN  
..           ...      ...           ...  
252          NaN      NaN           NaN  
253          NaN      NaN           NaN  
254          NaN      NaN           NaN  
255          NaN      NaN           NaN  
256          NaN      NaN           NaN 

In [101]:
validators['admissions_applicant'] = cur_validator

## Application Checklist

- GM_APPLICATION_CHECKLIST -> ['EXTERNAL_ID', 'ADMR_CODE_KEY']

In [107]:
baseline_filepath = "data/Prod/Baseline/BT_APPLICATION_CHECKLIST.csv"
validate_filepath = "data/Prod/Validate/Custom - Application Checklist.csv"
column_mapping = [
    {"baseline_col_name": "EXTERNAL_ID",
     "validate_col_name": "lang_externalid",
     "common_col_type": "",
    },
    {"baseline_col_name": "PIDM_KEY",
     "validate_col_name": "lang_pidmkey",
     "common_col_type": "",
    },
    {"baseline_col_name": "TERM_CODE_KEY",
     "validate_col_name": "lang_termcodekey",
     "common_col_type": "",
    },
    {"baseline_col_name": "APPL_NO_KEY",
     "validate_col_name": "lang_applicationnumberkey",
     "common_col_type": "",
    },
    {"baseline_col_name": "ADMR_CODE_KEY",
     "validate_col_name": "lang_admrcode",
     "common_col_type": "",
    },
    {"baseline_col_name": "ADMR_DESC",
     "validate_col_name": "lang_admrdescriptionorig",
     "common_col_type": "",
    },
    {"baseline_col_name": "ADMR_RECEIVED_DATE",
     "validate_col_name": "lang_admrreceiveddate",
     "common_col_type": "",
    },
    {"baseline_col_name": "ADMR_REQUIRED_IND",
     "validate_col_name": "lang_admrrequiredind",
     "common_col_type": "",
    },
    {"baseline_col_name": "ADMR_ITEM_DESC",
     "validate_col_name": "lang_admritemdescription",
     "common_col_type": "",
    }
]
baseline_date_cols = {"ADMR_RECEIVED_DATE": None,}  # "%d-%b-%y",
validate_date_cols = {"lang_admrreceiveddate": None,}
col_id = ['EXTERNAL_ID', 'ADMR_CODE_KEY']
baseline_encoding = "utf-8"
validate_encoding = "utf-8"
unify_text = False
text_cols = None
# unify_text = True
# text_cols = ['HOLD_REASON']

In [108]:
cur_validator = Validator(baseline_filepath=baseline_filepath,
                          validate_filepath=validate_filepath,
                          column_mapping=column_mapping,
                          baseline_date_cols=baseline_date_cols,
                          validate_date_cols=validate_date_cols,
                          col_id=col_id,
                          baseline_encoding=baseline_encoding,
                          validate_encoding=validate_encoding,
                          unify_text=unify_text,
                          text_cols=text_cols,
                         )

C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:319: UserWarning:     Expected data type does not match origin data type. Validation    will force expected type if present, otherwise, real type.
  warnings.warn("    Expected data type does not match origin data type. Validation"
C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:326: UserWarning: Warning:
        Dataset Baseline
        
                Column: EXTERNAL_ID
                    Real Type: int64
                    Expected Type: NA
                Column: PIDM_KEY
                    Real Type: int64
                    Expected Type: NA
                Column: TERM_CODE_KEY
                    Real Type: int64
                    Expected Type: NA
                Column: APPL_NO_KEY
                    Real Type: int64
                    Expected Type: NA
                Colu

In [109]:
cur_validator.name_mapping

{'lang_externalid': 'EXTERNAL_ID',
 'lang_pidmkey': 'PIDM_KEY',
 'lang_termcodekey': 'TERM_CODE_KEY',
 'lang_applicationnumberkey': 'APPL_NO_KEY',
 'lang_admrcode': 'ADMR_CODE_KEY',
 'lang_admrdescriptionorig': 'ADMR_DESC',
 'lang_admrreceiveddate': 'ADMR_RECEIVED_DATE',
 'lang_admrrequiredind': 'ADMR_REQUIRED_IND',
 'lang_admritemdescription': 'ADMR_ITEM_DESC'}

In [110]:
cur_validator.check_existence()

EXTERNAL_ID  ADMR_CODE_KEY  PIDM_KEY  TERM_CODE_KEY  APPL_NO_KEY   
0              False          False     False          False        False  \
1              False          False     False          False        False   
2              False          False     False          False        False   
3              False          False     False          False        False   
4              False          False     False          False        False   
...              ...            ...       ...            ...          ...   
1461872        False          False     False          False        False   
1461873        False          False     False          False        False   
1461874        False          False     False          False        False   
1461875        False          False     False          False        False   
1461876        False          False     False          False        False   

         ADMR_DESC  ADMR_RECEIVED_DATE  ADMR_REQUIRED_IND  ADMR_ITEM_DESC  
0            False               False              False           False  
1            False               False              False           False  
2            False               False              False           False  
3            False               False              False           False  
4            False               False              False           False  
...            ...                 ...                ...             ...  
1461872      False               False              False           False  
1461873      False               False              False           False  
1461874      False               False              False           False  
1461875      False               False              False           False  
1461876      False               False              False           False  

[1461877 rows x 9 columns]

In [111]:
cur_validator.existence_result.sum()

EXTERNAL_ID              0
ADMR_CODE_KEY            0
PIDM_KEY              2378
TERM_CODE_KEY         2378
APPL_NO_KEY           2378
ADMR_DESC             2378
ADMR_RECEIVED_DATE    1041
ADMR_REQUIRED_IND     1961
ADMR_ITEM_DESC        1229
dtype: int64

In [112]:
cur_validator.row_difference

2138

In [113]:
cur_validator.col_difference

{'origin_cols_not_in_target': set(),
 'target_cols_not_in_origin': {'bsi_admissionsapplicant',
  'lang_admrdescription',
  'lang_student',
  'lang_termdescription'}}

In [114]:
cur_validator.duplicated_rows

{'origin': 0, 'target': 0}

In [115]:
cur_validator.check_equality()

PIDM_KEY        TERM_CODE_KEY        APPL_NO_KEY        ADMR_DESC   
          origin target        origin target      origin target    origin   
0            NaN    NaN           NaN    NaN         NaN    NaN       NaN  \
4            NaN    NaN           NaN    NaN         NaN    NaN       NaN   
6            NaN    NaN           NaN    NaN         NaN    NaN       NaN   
8            NaN    NaN           NaN    NaN         NaN    NaN       NaN   
9            NaN    NaN           NaN    NaN         NaN    NaN       NaN   
...          ...    ...           ...    ...         ...    ...       ...   
1461794      NaN    NaN           NaN    NaN         NaN    NaN       NaN   
1461831      NaN    NaN           NaN    NaN         NaN    NaN       NaN   
1461847      NaN    NaN           NaN    NaN         NaN    NaN       NaN   
1461857      NaN    NaN           NaN    NaN         NaN    NaN       NaN   
1461867      NaN    NaN           NaN    NaN         NaN    NaN       NaN   

                ADMR_RECEIVED_DATE            ADMR_REQUIRED_IND          
        target              origin     target            origin target   
0          NaN 2018-09-18 17:26:31 2018-09-18               NaN    NaN  \
4          NaN 2004-05-13 09:30:03 2004-05-13               NaN    NaN   
6          NaN 1999-02-25 14:35:04 1999-02-25               NaN    NaN   
8          NaN 1999-02-25 14:35:04 1999-02-25               NaN    NaN   
9          NaN 2018-08-31 13:16:08 2018-08-31               NaN    NaN   
...        ...                 ...        ...               ...    ...   
1461794    NaN 2023-05-01 10:59:20 2023-05-01               NaN    NaN   
1461831    NaN 2023-04-25 09:54:44 2023-04-25               NaN    NaN   
1461847    NaN 2023-01-21 23:16:22 2023-01-21               NaN    NaN   
1461857    NaN 2023-04-23 13:14:26 2023-04-23               NaN    NaN   
1461867    NaN 2023-04-23 13:14:26 2023-04-23               NaN    NaN   

        ADMR_ITEM_DESC         
                origin target  
0                  NaN    NaN  
4                  NaN    NaN  
6                  NaN    NaN  
8                  NaN    NaN  
9                  NaN    NaN  
...                ...    ...  
1461794            NaN    NaN  
1461831            NaN    NaN  
1461847            NaN    NaN  
1461857            NaN    NaN  
1461867            NaN    NaN  

[196091 rows x 14 columns]

In [120]:
cur_validator.equality_result[cur_validator.equality_result[('ADMR_RECEIVED_DATE', 'target')].isna()]

PIDM_KEY        TERM_CODE_KEY        APPL_NO_KEY          
             origin target        origin target      origin target   
1244     90092214.0    NaN      202330.0    NaN         8.0    NaN  \
1245     90092214.0    NaN      202330.0    NaN         8.0    NaN   
1246     90092214.0    NaN      202330.0    NaN         8.0    NaN   
1247     90092214.0    NaN      202330.0    NaN         8.0    NaN   
1248     90092214.0    NaN      202330.0    NaN         8.0    NaN   
...             ...    ...           ...    ...         ...    ...   
1458679         NaN    NaN           NaN    NaN         NaN    NaN   
1458680         NaN    NaN           NaN    NaN         NaN    NaN   
1458682         NaN    NaN           NaN    NaN         NaN    NaN   
1459201         NaN    NaN           NaN    NaN         NaN    NaN   
1460721         NaN    NaN           NaN    NaN         NaN    NaN   

                              ADMR_DESC         ADMR_RECEIVED_DATE          
                                 origin target              origin target   
1244     Category 3 English Requirement    NaN                 NaT    NaT  \
1245       Proof of Grade 12 Graduation    NaN                 NaT    NaT   
1246                         LPI or LET    NaN 1999-02-25 14:35:04    NaT   
1247        Post-secondary Transcript 1    NaN 1994-08-18 00:00:00    NaT   
1248        Post-secondary Transcript 2    NaN                 NaT    NaT   
...                                 ...    ...                 ...    ...   
1458679                             NaN    NaN 2023-05-17 00:00:00    NaT   
1458680                             NaN    NaN 2023-05-17 00:00:00    NaT   
1458682                             NaN    NaN                 NaT    NaT   
1459201                             NaN    NaN 2023-05-15 00:00:00    NaT   
1460721                             NaN    NaN 2023-05-16 00:00:00    NaT   

        ADMR_REQUIRED_IND                         ADMR_ITEM_DESC   
                   origin target                          origin   
1244                    Y    NaN                             NaN  \
1245                    Y    NaN                             NaN   
1246                    Y    NaN           Test Date 27-MAR-1993   
1247                    Y    NaN       Kwantlen Polytechnic Univ   
1248                    Y    NaN                 Langara College   
...                   ...    ...                             ...   
1458679               NaN    NaN       CAPU/ENGL 100/B/Fall 2016   
1458680               NaN    NaN     CAPU/ENGL 103/B/Spring 2017   
1458682               NaN    NaN  CapU MATH101 Fall 2016 too old   
1459201               NaN    NaN                           LET 3   
1460721               NaN    NaN      LPN transcript rec'd (VCC)   

                               
                       target  
1244                      NaN  
1245                      NaN  
1246                      NaN  
1247                      NaN  
1248                      NaN  
...                       ...  
1458679                   NaN  
1458680                   NaN  
1458682                   NaN  
1459201                   NaN  
1460721  LPN transcript rec'd  

[3012 rows x 14 columns]

In [116]:
cur_validator.target_rows_not_in_origin

EXTERNAL_ID ADMR_CODE_KEY  PIDM_KEY  TERM_CODE_KEY  APPL_NO_KEY   
0     901234012023301          PST1       NaN            NaN          NaN  \
1     903225322023303          APFD       NaN            NaN          NaN   
2     903225322023303          GRAD       NaN            NaN          NaN   
3     903225322023303          SSIN       NaN            NaN          NaN   
4     903225322023303          SST1       NaN            NaN          NaN   
..                ...           ...       ...            ...          ...   
235   905962842023301          SST1       NaN            NaN          NaN   
236  9045233820241010          SST1       NaN            NaN          NaN   
237  9046723420233013          APFD       NaN            NaN          NaN   
238  9046723420233013          GRAD       NaN            NaN          NaN   
239  9046723420233013          SSIN       NaN            NaN          NaN   

    ADMR_DESC ADMR_RECEIVED_DATE ADMR_REQUIRED_IND ADMR_ITEM_DESC  
0         NaN                NaT               NaN            NaN  
1         NaN                NaT               NaN            NaN  
2         NaN                NaT               NaN            NaN  
3         NaN                NaT               NaN            NaN  
4         NaN                NaT               NaN            NaN  
..        ...                ...               ...            ...  
235       NaN                NaT               NaN            NaN  
236       NaN                NaT               NaN            NaN  
237       NaN                NaT               NaN            NaN  
238       NaN                NaT               NaN            NaN  
239       NaN                NaT               NaN            NaN  

[240 rows x 9 columns]

In [117]:
cur_validator.origin_rows_not_in_target

EXTERNAL_ID ADMR_CODE_KEY  PIDM_KEY  TERM_CODE_KEY  APPL_NO_KEY   
0     900922142023308          CAT3       NaN            NaN          NaN  \
1     900922142023308          GRAD       NaN            NaN          NaN   
2     900922142023308          LANG       NaN            NaN          NaN   
3     900922142023308          PST1       NaN            NaN          NaN   
4     900922142023308          PST2       NaN            NaN          NaN   
...               ...           ...       ...            ...          ...   
2373  905964312024101          GRAD       NaN            NaN          NaN   
2374  905964312024101          MADA       NaN            NaN          NaN   
2375  905964312024101          PST1       NaN            NaN          NaN   
2376  905964312024101          SSIE       NaN            NaN          NaN   
2377  905964312024101          SST1       NaN            NaN          NaN   

     ADMR_DESC ADMR_RECEIVED_DATE ADMR_REQUIRED_IND ADMR_ITEM_DESC  
0          NaN                NaT               NaN            NaN  
1          NaN                NaT               NaN            NaN  
2          NaN                NaT               NaN            NaN  
3          NaN                NaT               NaN            NaN  
4          NaN                NaT               NaN            NaN  
...        ...                ...               ...            ...  
2373       NaN                NaT               NaN            NaN  
2374       NaN                NaT               NaN            NaN  
2375       NaN                NaT               NaN            NaN  
2376       NaN                NaT               NaN            NaN  
2377       NaN                NaT               NaN            NaN  

[2378 rows x 9 columns]

In [118]:
validators['admissions_applicant'] = cur_validator

## Financial History

- GM_FINANCIAL_HISTORY -> ['PIDM_KEY', 'TRANSACTION_ID']

In [122]:
pd.read_csv("data/Prod/Baseline/BT_FINANCIAL_HISTORY.csv")

lang_pidmkey                          lang_student lang_termcodekey   
0            90539381  398089EF-3BF2-ED11-8849-000D3AFF1A9B           202230  \
1            90333568  2E5E0A96-36F2-ED11-8849-000D3AF39F3F           202230   
2            90558859  CF39F2D3-3BF2-ED11-8849-000D3AE86F09           202230   
3            90558859  CF39F2D3-3BF2-ED11-8849-000D3AE86F09           202230   
4            90225639  5FBCACA0-38F2-ED11-8849-000D3AE868A5           202230   
...               ...                                   ...              ...   
6724364      90571952  5D2D65E4-37F2-ED11-8849-002248AE057E           202320   
6724365      90565463  7F060249-37F2-ED11-8849-000D3AE862C8           202320   
6724366      90539164  AA53A450-36F2-ED11-8849-000D3AE8C6E5           202320   
6724367      90528623  9F9BEC90-38F2-ED11-8849-000D3AE86F09           202320   
6724368      90558613  123F73D8-3BF2-ED11-8849-000D3AE868A5           202320   

                         lang_termdescription  lang_transactionid   
0        56A9CC90-35F2-ED11-8849-002248AE080F                  73  \
1        56A9CC90-35F2-ED11-8849-002248AE080F                  62   
2        56A9CC90-35F2-ED11-8849-002248AE080F                  17   
3        56A9CC90-35F2-ED11-8849-002248AE080F                  18   
4        56A9CC90-35F2-ED11-8849-002248AE080F                  56   
...                                       ...                 ...   
6724364  58A9CC90-35F2-ED11-8849-002248AE080F                  69   
6724365  58A9CC90-35F2-ED11-8849-002248AE080F                  91   
6724366  58A9CC90-35F2-ED11-8849-002248AE080F                 188   
6724367  58A9CC90-35F2-ED11-8849-002248AE080F                 382   
6724368  58A9CC90-35F2-ED11-8849-002248AE080F                 172   

        lang_detailcode      lang_detaildescription  lang_charge   
0                  STFF       200000232 - ECON 1221          NaN  \
1                  STFF       100182782 - PUBL 1900          NaN   
2                  STFF       200000875 - CPSC 4800          NaN   
3                  STFF       200000875 - DANA 4800          NaN   
4                  STFF       100092357 - DSGN 1255          NaN   
...                 ...                         ...          ...   
6724364            LSU2  LSU Burs,Schol&Awards Fund        -2.37   
6724365            LSU2  LSU Burs,Schol&Awards Fund        -2.37   
6724366            LSU2  LSU Burs,Schol&Awards Fund        -2.37   
6724367            LSU2  LSU Burs,Schol&Awards Fund        -2.37   
6724368            HSCI     HSCI-55051 Mat Fee HSCI       -12.85   

         lang_payment  lang_balance lang_document           lang_effectivedate  
0             -316.53          0.00           NaN  2022-07-20 00:00:00.0000000  
1              530.00          0.00           NaN  2022-09-21 00:00:00.0000000  
2              706.47          0.00           NaN  2022-09-08 00:00:00.0000000  
3              706.47          0.00           NaN  2022-09-08 00:00:00.0000000  
4              316.53          0.00           NaN  2022-09-08 00:00:00.0000000  
...               ...           ...           ...                          ...  
6724364           NaN          0.00           NaN  2023-04-24 00:00:00.0000000  
6724365           NaN         -2.37           NaN  2023-04-24 00:00:00.0000000  
6724366           NaN          0.00           NaN  2023-04-24 00:00:00.0000000  
6724367           NaN         -2.37           NaN  2023-04-24 00:00:00.0000000  
6724368           NaN          0.00           NaN  2023-04-24 00:00:00.0000000  

[6724369 rows x 12 columns]

In [124]:
baseline_filepath = "data/Prod/Baseline/BT_FINANCIAL_HISTORY.csv"
validate_filepath = "data/Prod/Validate/Custom - Financial History.csv"
column_mapping = [
    {"baseline_col_name": "PIDM_KEY",
     "validate_col_name": "lang_pidmkey",
     "common_col_type": "",
    },
    {"baseline_col_name": "TRANSACTION_ID",
     "validate_col_name": "lang_transactionid",
     "common_col_type": "",
    },
    {"baseline_col_name": "TERM_CODE_KEY",
     "validate_col_name": "lang_termcodekey",
     "common_col_type": "",
    },
    {"baseline_col_name": "DETAIL_CODE",
     "validate_col_name": "lang_detailcode",
     "common_col_type": "",
    },
    {"baseline_col_name": "DESCRIPTION",
     "validate_col_name": "lang_detaildescription",
     "common_col_type": "",
    },
    {"baseline_col_name": "CHARGE",
     "validate_col_name": "lang_charge",
     "common_col_type": "",
    },
    {"baseline_col_name": "PAYMENT",
     "validate_col_name": "lang_payment",
     "common_col_type": "",
    },
    {"baseline_col_name": "BALANCE",
     "validate_col_name": "lang_balance",
     "common_col_type": "",
    },
    {"baseline_col_name": "DOCUMENT",
     "validate_col_name": "lang_document",
     "common_col_type": "",
    },
    {"baseline_col_name": "EFFECTIVE_DATE",
     "validate_col_name": "lang_effectivedate",
     "common_col_type": "",
    }
]
baseline_date_cols = {"EFFECTIVE_DATE": None,}  # "%d-%b-%y",
validate_date_cols = {"lang_effectivedate": None,}
col_id = ['PIDM_KEY', 'TRANSACTION_ID']
baseline_encoding = "utf-8"
validate_encoding = "utf-8"
unify_text = False
text_cols = None
# unify_text = True
# text_cols = ['HOLD_REASON']

In [125]:
cur_validator = Validator(baseline_filepath=baseline_filepath,
                          validate_filepath=validate_filepath,
                          column_mapping=column_mapping,
                          baseline_date_cols=baseline_date_cols,
                          validate_date_cols=validate_date_cols,
                          col_id=col_id,
                          baseline_encoding=baseline_encoding,
                          validate_encoding=validate_encoding,
                          unify_text=unify_text,
                          text_cols=text_cols,
                         )

C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:36: DtypeWarning: Columns (2,8) have mixed types. Specify dtype option on import or set low_memory=False.
  temp_df = pd.read_csv(filepath, encoding=encoding)
C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:319: UserWarning:     Expected data type does not match origin data type. Validation    will force expected type if present, otherwise, real type.
  warnings.warn("    Expected data type does not match origin data type. Validation"
C:\Users\dhernandezvarg00\OneDrive - Langara College\Work\Langara-Business_Data_Analyst\Work\CRM\Data_Validation\utils.py:326: UserWarning: Warning:
        Dataset Baseline
        
                Column: PIDM_KEY
                    Real Type: int64
                    Expected Type: NA
                Column: TRANSACTION_ID
                    Real Type: int6

In [126]:
cur_validator.name_mapping

{'lang_pidmkey': 'PIDM_KEY',
 'lang_transactionid': 'TRANSACTION_ID',
 'lang_termcodekey': 'TERM_CODE_KEY',
 'lang_detailcode': 'DETAIL_CODE',
 'lang_detaildescription': 'DESCRIPTION',
 'lang_charge': 'CHARGE',
 'lang_payment': 'PAYMENT',
 'lang_balance': 'BALANCE',
 'lang_document': 'DOCUMENT',
 'lang_effectivedate': 'EFFECTIVE_DATE'}

In [127]:
cur_validator.check_existence()

PIDM_KEY  TRANSACTION_ID  TERM_CODE_KEY  DETAIL_CODE  DESCRIPTION   
0           False           False          False        False        False  \
1           False           False          False        False        False   
2           False           False          False        False        False   
3           False           False          False        False        False   
4           False           False          False        False        False   
...           ...             ...            ...          ...          ...   
6729661     False           False           True         True         True   
6729662     False           False           True         True         True   
6729663     False           False           True         True         True   
6729664     False           False           True         True         True   
6729665     False           False           True         True         True   

         CHARGE  PAYMENT  BALANCE  DOCUMENT  EFFECTIVE_DATE  
0         False    False    False     False           False  
1         False    False    False     False           False  
2         False    False    False     False           False  
3         False    False    False     False           False  
4         False    False    False     False           False  
...         ...      ...      ...       ...             ...  
6729661    True    False     True     False            True  
6729662   False     True     True     False           False  
6729663    True    False     True     False            True  
6729664    True    False     True     False            True  
6729665   False     True     True      True            True  

[6729666 rows x 10 columns]

In [128]:
cur_validator.existence_result.sum()

PIDM_KEY             0
TRANSACTION_ID       0
TERM_CODE_KEY     5405
DETAIL_CODE       5405
DESCRIPTION       5405
CHARGE            3427
PAYMENT           1978
BALANCE           5405
DOCUMENT           997
EFFECTIVE_DATE    5361
dtype: int64

In [129]:
cur_validator.row_difference

5297

In [130]:
cur_validator.col_difference

{'origin_cols_not_in_target': set(),
 'target_cols_not_in_origin': {'lang_student', 'lang_termdescription'}}

In [131]:
cur_validator.duplicated_rows

{'origin': 0, 'target': 0}

In [132]:
cur_validator.check_equality()

TERM_CODE_KEY         DETAIL_CODE          
               origin  target      origin target   
39                NaN     NaN         NaN    NaN  \
40                NaN     NaN         NaN    NaN   
41              20032  020032         NaN    NaN   
44              20062  020062         NaN    NaN   
48              20062  020062         NaN    NaN   
...               ...     ...         ...    ...   
6729661        020233     NaN        CCL1    NaN   
6729662        020233     NaN        ESMC    NaN   
6729663        020232     NaN        SCP1    NaN   
6729664        020232     NaN        SCP2    NaN   
6729665        020232     NaN        RDVM    NaN   

                            DESCRIPTION        CHARGE        PAYMENT          
                                 origin target origin target  origin target   
39                                  NaN    NaN    NaN    NaN     NaN    NaN  \
40                                  NaN    NaN    NaN    NaN     NaN    NaN   
41                                  NaN    NaN    NaN    NaN     NaN    NaN   
44                                  NaN    NaN    NaN    NaN     NaN    NaN   
48                                  NaN    NaN    NaN    NaN     NaN    NaN   
...                                 ...    ...    ...    ...     ...    ...   
6729661  CSSCL-55036 Int'l Tuition Fees    NaN  155.0    NaN     NaN    NaN   
6729662          MC-Shopify Order#24899    NaN    NaN    NaN   155.0    NaN   
6729663   CSSCP-55033 CS Summer Camp Pm    NaN  460.0    NaN     NaN    NaN   
6729664     CSSCP-55033 CS Admin Charge    NaN   35.0    NaN     NaN    NaN   
6729665                    eSelect Visa    NaN    NaN    NaN   495.0    NaN   

        BALANCE        DOCUMENT             EFFECTIVE_DATE             
         origin target   origin target              origin     target  
39          NaN    NaN      NaN    NaN 2003-04-29 16:31:04 2003-04-29  
40          NaN    NaN      NaN    NaN 2003-04-29 16:31:04 2003-04-29  
41          NaN    NaN      NaN    NaN                 NaT        NaT  
44          NaN    NaN      NaN    NaN                 NaT        NaT  
48          NaN    NaN      NaN    NaN                 NaT        NaT  
...         ...    ...      ...    ...                 ...        ...  
6729661     0.0    NaN      NaN    NaN 2023-05-17 00:00:00        NaT  
6729662     0.0    NaN      NaN    NaN                 NaT        NaT  
6729663     0.0    NaN      NaN    NaN 2023-05-17 00:00:00        NaT  
6729664     0.0    NaN      NaN    NaN 2023-05-17 00:00:00        NaT  
6729665     0.0    NaN   049215    NaN 2023-05-17 17:15:33        NaT  

[4181795 rows x 16 columns]

In [133]:
cur_validator.equality_result[cur_validator.equality_result[('EFFECTIVE_DATE', 'target')].isna()]

TERM_CODE_KEY         DETAIL_CODE          
               origin  target      origin target   
41              20032  020032         NaN    NaN  \
44              20062  020062         NaN    NaN   
48              20062  020062         NaN    NaN   
55              20063  020063         NaN    NaN   
56              20063  020063         NaN    NaN   
...               ...     ...         ...    ...   
6729661        020233     NaN        CCL1    NaN   
6729662        020233     NaN        ESMC    NaN   
6729663        020232     NaN        SCP1    NaN   
6729664        020232     NaN        SCP2    NaN   
6729665        020232     NaN        RDVM    NaN   

                            DESCRIPTION        CHARGE        PAYMENT          
                                 origin target origin target  origin target   
41                                  NaN    NaN    NaN    NaN     NaN    NaN  \
44                                  NaN    NaN    NaN    NaN     NaN    NaN   
48                                  NaN    NaN    NaN    NaN     NaN    NaN   
55                                  NaN    NaN    NaN    NaN     NaN    NaN   
56                                  NaN    NaN    NaN    NaN     NaN    NaN   
...                                 ...    ...    ...    ...     ...    ...   
6729661  CSSCL-55036 Int'l Tuition Fees    NaN  155.0    NaN     NaN    NaN   
6729662          MC-Shopify Order#24899    NaN    NaN    NaN   155.0    NaN   
6729663   CSSCP-55033 CS Summer Camp Pm    NaN  460.0    NaN     NaN    NaN   
6729664     CSSCP-55033 CS Admin Charge    NaN   35.0    NaN     NaN    NaN   
6729665                    eSelect Visa    NaN    NaN    NaN   495.0    NaN   

        BALANCE        DOCUMENT             EFFECTIVE_DATE         
         origin target   origin target              origin target  
41          NaN    NaN      NaN    NaN                 NaT    NaT  
44          NaN    NaN      NaN    NaN                 NaT    NaT  
48          NaN    NaN      NaN    NaN                 NaT    NaT  
55          NaN    NaN      NaN    NaN                 NaT    NaT  
56          NaN    NaN      NaN    NaN                 NaT    NaT  
...         ...    ...      ...    ...                 ...    ...  
6729661     0.0    NaN      NaN    NaN 2023-05-17 00:00:00    NaT  
6729662     0.0    NaN      NaN    NaN                 NaT    NaT  
6729663     0.0    NaN      NaN    NaN 2023-05-17 00:00:00    NaT  
6729664     0.0    NaN      NaN    NaN 2023-05-17 00:00:00    NaT  
6729665     0.0    NaN   049215    NaN 2023-05-17 17:15:33    NaT  

[456553 rows x 16 columns]

In [134]:
cur_validator.target_rows_not_in_origin

PIDM_KEY  TRANSACTION_ID TERM_CODE_KEY DETAIL_CODE DESCRIPTION  CHARGE   
0    90162400               1           NaN         NaN         NaN     NaN  \
1    90162400               2           NaN         NaN         NaN     NaN   
2    90162400               3           NaN         NaN         NaN     NaN   
3    90162400               4           NaN         NaN         NaN     NaN   
4    90162400               5           NaN         NaN         NaN     NaN   
..        ...             ...           ...         ...         ...     ...   
103  90594997               2           NaN         NaN         NaN     NaN   
104  90594997               3           NaN         NaN         NaN     NaN   
105  90595932               1           NaN         NaN         NaN     NaN   
106  90595932               2           NaN         NaN         NaN     NaN   
107  90595932               3           NaN         NaN         NaN     NaN   

     PAYMENT  BALANCE DOCUMENT EFFECTIVE_DATE  
0        NaN      NaN      NaN            NaT  
1        NaN      NaN      NaN            NaT  
2        NaN      NaN      NaN            NaT  
3        NaN      NaN      NaN            NaT  
4        NaN      NaN      NaN            NaT  
..       ...      ...      ...            ...  
103      NaN      NaN      NaN            NaT  
104      NaN      NaN      NaN            NaT  
105      NaN      NaN      NaN            NaT  
106      NaN      NaN      NaN            NaT  
107      NaN      NaN      NaN            NaT  

[108 rows x 10 columns]

In [135]:
cur_validator.origin_rows_not_in_target

PIDM_KEY  TRANSACTION_ID TERM_CODE_KEY DETAIL_CODE DESCRIPTION  CHARGE   
0     90068143              47           NaN         NaN         NaN     NaN  \
1     90068143              48           NaN         NaN         NaN     NaN   
2     90078182               1           NaN         NaN         NaN     NaN   
3     90089785             399           NaN         NaN         NaN     NaN   
4     90089785             400           NaN         NaN         NaN     NaN   
...        ...             ...           ...         ...         ...     ...   
5400  90596437               1           NaN         NaN         NaN     NaN   
5401  90596437               2           NaN         NaN         NaN     NaN   
5402  90596439               1           NaN         NaN         NaN     NaN   
5403  90596439               2           NaN         NaN         NaN     NaN   
5404  90596439               3           NaN         NaN         NaN     NaN   

      PAYMENT  BALANCE DOCUMENT EFFECTIVE_DATE  
0         NaN      NaN      NaN            NaT  
1         NaN      NaN      NaN            NaT  
2         NaN      NaN      NaN            NaT  
3         NaN      NaN      NaN            NaT  
4         NaN      NaN      NaN            NaT  
...       ...      ...      ...            ...  
5400      NaN      NaN      NaN            NaT  
5401      NaN      NaN      NaN            NaT  
5402      NaN      NaN      NaN            NaT  
5403      NaN      NaN      NaN            NaT  
5404      NaN      NaN      NaN            NaT  

[5405 rows x 10 columns]

In [136]:
validators['admissions_applicant'] = cur_validator

## Program History

- GM_PROGRAM_HISTORY_DETAIL -> ['PIDM_KEY', 'TERM_CODE_KEY']

In [ ]:
column_mapping = [
    {"baseline_col_name": "PIDM_KEY",
     "baseline_col_type": "",
     "validate_col_name": "lang_pidmkey",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "TERM_CODE_KEY",
     "baseline_col_type": "",
     "validate_col_name": "lang_termcodekey",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "ID",
     "baseline_col_type": "",
     "validate_col_name": "lang_id",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "STUDENT_STATUS",
     "baseline_col_type": "",
     "validate_col_name": "lang_studentstatusorig",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "PROGRAM_CODE",
     "baseline_col_type": "",
     "validate_col_name": "lang_programcode",
     "validate_col_type": "",
     "common_col_type": "",
     }, 
    {"baseline_col_name": "PROGRAM_NAME",
     "baseline_col_type": "",
     "validate_col_name": "lang_programdescriptionorig",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "MAJOR",
     "baseline_col_type": "",
     "validate_col_name": "lang_major",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "CONCENTRATION",
     "baseline_col_type": "",
     "validate_col_name": "lang_concentration",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "TOTAL_CREDITS",
     "baseline_col_type": "",
     "validate_col_name": "lang_totalcredits",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "ACADEMIC_STANDING",
     "baseline_col_type": "",
     "validate_col_name": "lang_academicstanding",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "ACAD_STANDING_DESC",
     "baseline_col_type": "",
     "validate_col_name": "lang_academicstandingdescriptionorig",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "RESD_CODE",
     "baseline_col_type": "",
     "validate_col_name": "lang_residentcode",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "RESD_DESC",
     "baseline_col_type": "",
     "validate_col_name": "lang_residentnameorig",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "STUDENT_TYPE_CODE",
     "baseline_col_type": "",
     "validate_col_name": "lang_studenttypecode",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "STUDENT_TYPE",
     "baseline_col_type": "",
     "validate_col_name": "lang_studenttype",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "TERM_GPA",
     "baseline_col_type": "",
     "validate_col_name": "mshied_termgpa",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "ENROLMENT_STATUS",
     "baseline_col_type": "",
     "validate_col_name": "lang_enrolmentstatus",
     "validate_col_type": "",
     "common_col_type": "",
     },   
    {"baseline_col_name": "CMIF_FEE_PAID",
     "baseline_col_type": "",
     "validate_col_name": "lang_cmiffeepaid",
     "validate_col_type": "",
     "common_col_type": "",
     }
]

## Student Data

- GM_STUDENT_DATA -> ['PIDM_KEY']

In [ ]:
column_mapping = [
    {"baseline_col_name": "PIDM_KEY",
     "baseline_col_type": "",
     "validate_col_name": "lang_id",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "ID",
     "baseline_col_type": "",
     "validate_col_name": "bsi_studentid",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "LAST_NAME",
     "baseline_col_type": "",
     "validate_col_name": "lastname",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "FIRST_NAME",
     "baseline_col_type": "",
     "validate_col_name": "firstname",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "MIDDLE_NAME",
     "baseline_col_type": "",
     "validate_col_name": "middlename",
     "validate_col_type": "",
     "common_col_type": "",
     }, 
    {"baseline_col_name": "NAME_PREFIX",
     "baseline_col_type": "",
     "validate_col_name": "salutation",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "NAME_SUFFIX",
     "baseline_col_type": "",
     "validate_col_name": "lang_namesuffix",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "SURNAME_PREFIX",
     "baseline_col_type": "",
     "validate_col_name": "lang_surnameprefix",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "BIRTH_DATE",
     "baseline_col_type": "",
     "validate_col_name": "birthdate",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "AGE",
     "baseline_col_type": "",
     "validate_col_name": "lang_age",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "GENDER",
     "baseline_col_type": "",
     "validate_col_name": "lang_genderorig",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "DECEASED_IND",
     "baseline_col_type": "",
     "validate_col_name": "bsi_deceasedind",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "DECEASED_DATE",
     "baseline_col_type": "",
     "validate_col_name": "lang_deceaseddate",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "STREET1_LINE1",
     "baseline_col_type": "",
     "validate_col_name": "address1_line1",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "STREET1_LINE2",
     "baseline_col_type": "",
     "validate_col_name": "address1_line2",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "STREET1_LINE3",
     "baseline_col_type": "",
     "validate_col_name": "address1_line3",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "CITY1",
     "baseline_col_type": "",
     "validate_col_name": "address1_city",
     "validate_col_type": "",
     "common_col_type": "",
     },   
    {"baseline_col_name": "STATE1",
     "baseline_col_type": "",
     "validate_col_name": "address1_stateorprovince",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "ZIP1",
     "baseline_col_type": "",
     "validate_col_name": "address1_postalcode",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "NATN_CODE1",
     "baseline_col_type": "",
     "validate_col_name": "lang_countrycode",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "NATN_DESC1",
     "baseline_col_type": "",
     "validate_col_name": "lang_countryorig",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "PREFERRED_NAME",
     "baseline_col_type": "",
     "validate_col_name": "bsi_preferredname",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "VETC_NUMBER",
     "baseline_col_type": "",
     "validate_col_name": "lang_vetcnumber",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "RELG_DESC",
     "baseline_col_type": "",
     "validate_col_name": "lang_primarylanguage",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "CITZ_CODE",
     "baseline_col_type": "",
     "validate_col_name": "lang_citizenshipcode",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "COLL_EMAIL",
     "baseline_col_type": "",
     "validate_col_name": "lang_collemail",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "PREF_EMAIL",
     "baseline_col_type": "",
     "validate_col_name": "bsi_banneremailpreferred",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "STUD_EMAIL",
     "baseline_col_type": "",
     "validate_col_name": "lang_studentemail",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "AR_ACCOUNT_BALANCE",
     "baseline_col_type": "",
     "validate_col_name": "lang_araccountbalance",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "AR_AMOUNT_DUE",
     "baseline_col_type": "",
     "validate_col_name": "lang_aramountdue",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "PERSON_TYPE",
     "baseline_col_type": "",
     "validate_col_name": "lang_persontypeorig",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "NATN_CODE_CITIZEN",
     "baseline_col_type": "",
     "validate_col_name": "lang_nationalitycode",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "NATN_CODE_CITIZEN_DESC",
     "baseline_col_type": "",
     "validate_col_name": "lang_nationalityorigdata",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "PRIMARY_PHONE",
     "baseline_col_type": "",
     "validate_col_name": "telephone1",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "MOBILE_PHONE",
     "baseline_col_type": "",
     "validate_col_name": "mobilephone",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "INTERNATIONAL_PHONE",
     "baseline_col_type": "",
     "validate_col_name": "telephone2",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "AGENT_EMAIL",
     "baseline_col_type": "",
     "validate_col_name": "lang_agentemail",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "INTERNATIONAL_VISA_NUMBER",
     "baseline_col_type": "",
     "validate_col_name": "lang_internationalvisanumber",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "INTERNATIONAL_VISA_TYPE",
     "baseline_col_type": "",
     "validate_col_name": "lang_internationalvisatype",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "VISA_START_DATE",
     "baseline_col_type": "",
     "validate_col_name": "lang_visastartdate",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "VISA_END_DATE",
     "baseline_col_type": "",
     "validate_col_name": "lang_visaenddate",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "EMERGENCY_FIRST_NAME",
     "baseline_col_type": "",
     "validate_col_name": "lang_emergencyfirstname",
     "validate_col_type": "",
     "common_col_type": "",
     },
     {"baseline_col_name": "EMERGENCY_LAST_NAME",
     "baseline_col_type": "",
     "validate_col_name": "lang_emergencylastname",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "EMERGENCY_PHONE",
     "baseline_col_type": "",
     "validate_col_name": "lang_emergencyphone",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "LAST_TERM",
     "baseline_col_type": "",
     "validate_col_name": "lang_lasttermorig",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "LAST_TERM_GPA",
     "baseline_col_type": "",
     "validate_col_name": "lang_lasttermgpa",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "CGPA",
     "baseline_col_type": "",
     "validate_col_name": "lang_cgpa",
     "validate_col_type": "",
     "common_col_type": "",
     },
    {"baseline_col_name": "LAST_ACADEMIC_STANDING",
     "baseline_col_type": "",
     "validate_col_name": "lang_lastacademicstanding",
     "validate_col_type": "",
     "common_col_type": "",
     }


]

## Student Registration

- GM_STUDENT_REGISTRATION_DETAIL -> ['PIDM_KEY', 'TERM_CODE_KEY', 'CRN_KEY'] *Only data for next year (20232, 202320, 20233, 20241)